name: Build and Release

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: |
        sudo pacman -Sy --noconfirm git base-devel
        
    - name: Build package
      run: |
        git clone https://aur.archlinux.org/packages/cosmic-epoch-git.git
        cd PACKAGE_NAME
        makepkg -si --noconfirm
        
    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
        
    - name: Upload artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./PACKAGE_NAME/*.pkg.tar.zst
        asset_name: PACKAGE_NAME.pkg.tar.zst
        asset_content_type: application/octet-stream
