name: Build and lint
on:
  push:
    paths:
      - 'PKGBUILD'
      - '.github/workflows/main.yml'
  workflow_dispatch:
jobs:
  cosmic-epoch-git:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build (GCC)
      id: makepkg
      uses: CachyOS/pkgbuild-action@master
      with:
        envvars: CFLAGS="-march=silvermont -O3 -pipe -fgraphite-identity -floop-strip-mine -floop-nest-optimize -fno-semantic-interposition -fipa-pta -flto -fdevirtualize-at-ltrans -flto-partition=one" CXXFLAGS="${CFLAGS}" CMAKE_C_COMPILER="command gcc $CFLAGS" CMAKE_LINKER="command ld $LDFLAGS" LDFLAGS="-Wl,-O1,--sort-common,--as-needed,-z,now ${CFLAGS}"
        pkgdir: "./"
        namcapExcludeRules: "invalidstartdir"
        makepkgArgs: "--skipchecksums --skippgpcheck --noconfirm -s"
    - uses: actions/upload-artifact@v3
      with:
        path: "./*.zst"
